#!/bin/bash
if [ -e $HOME/vnc_jobid ]; then
   scancel `cat $HOME/vnc_jobid`
   rm -f $HOME/vnc_jobid
   rm -f $HOME/vnc_info
   rm -f $HOME/jobid
else
   echo "$HOME/vnc_jobid file does not exist"
fi
