#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "matlab"
module-whatis "Version: VERSION"
prepend-path PATH /opt/matlab/VERSION//bin
setenv MLM_LICENSE_FILE /opt/matlab/VERSION/licenses/network.lic:/opt/matlab/VERSION/licenses/license.dat 
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )

